// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Creat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creat));
        
        string IMigrationMetadata.Id
        {
            get { return "201912130901224_Creat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
