// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Update20191125446 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update20191125446));
        
        string IMigrationMetadata.Id
        {
            get { return "201906290852087_Update20191125446"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
